name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (Optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:latest

      # Step 4: Tag and push the Docker image to the registry (Optional)
      - name: Tag the Docker image
        run: docker tag my-image-name:latest bhuvanbhoge/wisecow:latest

      - name: Push the Docker image
        run: docker push bhuvanbhoge/wisecow:latest:latest

